---
- name: Check file status
  hosts: all

  tasks:
    - name: File need to check
      stat:
        path: /etc/hosts
      register: fs

    - name: Show result
      debug:
        msg: File attributes {{ fs }}
