---
- name: Install httpd and open firewall port
  hosts: all

  tasks:
    - name: Install apache2
      dnf:
        name: httpd
        state: present

    - name: Start apache2
      service:
        name: httpd
        state: started

    - name: Install firewalld
      dnf:
        name: firewalld
        state: present

    - name: Start firewalld
      service:
        name: firewalld
        state: started

    - name: Open port
      firewalld: 
        service: http
        permanent: true
        state: enabled

    - name: Restart firewalld to reload service
      service:
        name: firewalld
        state: reloaded

