---
- name: Download tomcat and place in a directory
  hosts: all

  tasks:
    - name: Create directory for tomcat
      file:
        path: /opt/tomcat
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Download Tomcat from URL
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.105/bin/apache-tomcat-9.0.105.tar.gz
        dest: /opt/tomcat
        mode: 0755
        owner: root
        group: root
